### ISSUE TITLE
Reporting a small typescript bug + requesting a feature

### ISSUE THREAD

**Issue by alaa-paramount** [pedrohenriquepires/react-simple-dialogs#1]
Hi,

First of all I would like to thank you for great work you done here :)

I'm reporting a small typescript bug <any> for the prompt dialog:
await simplePrompt() <--- typescript error returns any instead of string

"
Unsafe assignment of an `any` value.eslint[@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)
(alias) simplePrompt(props: PromptOptions): Promise<PromptResult>
import simplePrompt
"

---

In addition, requesting a new feature about the "inputLabel" for the prompt dialog:
the label is currently above the textbox input which is not that usefull,
maybe it's better to put the label inside the textbox of the prompt, so we will receive default input for "save file dialog" for example

**Comment by pedrohenriquepires** [comment]
Hi @alaa-paramount, thanks for your feedback and for report this issue!

I just released a new patch (1.2.3) in order to fix this issue, can you upgrade your version and test it again?

Let me know if this worked for you!

**Comment by alaa-paramount** [comment]
> Hi @alaa-paramount, thanks for your feedback and for report this issue!
> 
> I just released a new minor version (1.2.3) in order to fix this issue, can you upgrade your version and test it again?
> 
> Let me know if this worked for you!


Hi pedrohenriquepires,

Thank you, the "Unsafe assignment of an 'any'" is resolved!
